pcm.camilla_loopback {
    type plug
    slave {
        pcm "hw:Loopback,1,0"
        channels 2
        rate 48000
        format S16_LE
    }
}

pcm.!default {
    type plug
    slave.pcm "camilla_loopback"
}

